export {localizationInitialize} from './localization/initialize'
export {addTranslations, addTranslationsRest} from './localization/addtranslations'
export {setLanguage} from './localization/setLanguage'
export {goToPage} from './navigate'
export {setLanguageRequestedBySearch} from './localization/setLanguageRequestedBySearch'
export {setAnimation} from './setAnimation'
